### ISSUE TITLE
required: true property in model definition does not set created columns to NOT NULL

### ISSUE THREAD

**Issue by sgbenner** [intel/sails-mssql#12]
When defining a model, sails supports a required: true/false field as a property of a field attribute. When setting a field to required: true, the mssql adapter does not create the field as NOT NULL in the database.
This should be a fairly straight forward fix, but I cannot see where sails passes this property to the mssql adapter. I can see sails passing the field name, type and column Type, but it does not pass the required property, which could then be read and dynamically set the field to NULL or NOT NULL based on whether the field is specified as required.

**Comment by sgbenner** [comment]
@davepreston - I'd be happy to help look into this. If you're able to give some direction on what code needs updated, I can try to figure this out. Thanks.

**Comment by davepreston** [comment]
been a while since I've looked at that part of the code, but I believe it's in the lib/sql.js file in the _schema function.

**Comment by davepreston** [comment]
I'm going to close this one. Although it's true that sails doesn't set the column to not null in the DB, the "required" attribute is enforced by sails itself (before ever getting to sql server).
