### ISSUE TITLE
DB Transactions

### ISSUE THREAD

**Issue by scottsmith8** [intel/sails-mssql#21]
Hi guys,
I've been enjoying using this however I was wondering if there is support for database transactions as described https://sailsjs.com/documentation/reference/waterline-orm/datastores/transaction.

Thanks!
Sam

**Comment by davepreston** [comment]
Short answer yes :).
I've only used transactions via sails for very basic scenarios. Meaning if you have extravagant needs I may need your help enhancing the current capabilities.
That said, in my testing I am able to begin transactions and if an error is thrown it will roll back.

Please let me know if you find specific issues and we can reopen this issue.
