### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by khalilTN** [intel/sails-mssql#28]
Hello,
I'm using sails-mssql@1.0.2 with waterline@0.11.11 in standalone mode.
When i try to create a record, i get this error:

> pkType = connections[connection].collections[collection].attributes[key].type;
>          TypeError: Cannot read property 'type' of undefined
>          at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\sails-mssql\lib\adapter.js:675:82
>     at Array.forEach (<anonymous>)
>     at Object.getPrimaryKeyType (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\sails-mssql\lib\adapter.js:672:79)
>     at Object.create (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\sails-mssql\lib\adapter.js:585:28)
>     at module.exports.create (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\lib\waterline\adapter\dql.js:84:13)
>     at child.createValues (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\lib\waterline\query\dql\create.js:220:16)
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\lib\waterline\query\dql\create.js:74:20
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:726:13
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:52:16
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:269:32
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:44:16
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:723:17
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:167:37
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:52:16
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:269:32
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:44:16
>     at child.<anonymous> (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\lib\waterline\utils\schema.js:152:44)
>     at fn (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\lib\waterline\utils\callbacksRunner.js:41:10)
>     at D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:181:20
>     at iterate (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:262:13)
>     at Object.async.forEachOfSeries.async.eachOfSeries (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:281:9)
>     at Object.async.forEachSeries.async.eachSeries (D:\khalil.aifaoui\projets\SIAIT\siait.v3\trunk\server\node_modules\waterline\node_modules\async\lib\async.js:214:22)

It seems that it's a probleme of case sensitivness between model definition object
`connections[connection].collections[collection].definition`
and model attributes 
`connections[connection].collections[collection].attributes`

Function getPrimaryKeyType try to find an attribute with "ID"(uppercase) inside attributes object wich contains an "id"attribute (lower case) 

Thank you !

**Comment by khalilTN** [comment]
The definition object seems to contain column names and not attribute names

**Comment by davepreston** [comment]
Can you help me replicate the issue? I'm not clear on when you're seeing this issue.
