### ISSUE TITLE
Connection failed in LAN.

### ISSUE THREAD

**Issue by eckolosst** [intel/sails-mssql#5]
Hi. I am trying to establish a connection with my database and the following error appears:

> error: A hook (`orm`) failed to load!
> error: 
> error: There was an error attempting to load `sails-mssql`.
> (Sails attempted to load this adapter because it is referenced by a datastore (`default`) in this app's configuration)
> Please ensure that `sails-mssql` is a valid Sails/Waterline adapter, and that it is installed in this app.
> 
> Error details:
> Error: Cannot find module 'machinepack-mssql'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/home/myProyect/node_modules/sails-mssql/lib/adapter.js:7:19)....

I tried the following URLs in datastore.js but I got the same error both times:
url: 'mssql://username:password@url:port/databasename'
url: 'WATERLINE_ADAPTER_TESTS_URL=mssql://username:password@url:port/databasename'

**Comment by davepreston** [comment]
good catch! thanks. yes it will be added to the dependency, I'd love a PR
if you have one!

--dave

**Comment by eckolosst** [comment]
Yes of course. Give me a few minutes.

**Comment by eckolosst** [comment]
I need permissions to upload the branch with the fix.

**Comment by davepreston** [comment]
resolved in PR #8 
again, sorry for my absence for the last few months (health issues :( )
