### ISSUE TITLE
Type number not supported  in models.

### ISSUE THREAD

**Issue by eckolosst** [intel/sails-mssql#6]
I did  try define some models atributte as **number type**. And when I run **sails lift** get the next error:
> error: { Exception: `sendNativeQuery` failed ("queryFailed").  The database returned an error when attempting to execute the native query.
> Additional data:
> 
> { error:
>    { RequestError: Incorrect syntax near the keyword 'NULL'.
>        at handleError (/home/myproyect/node_modules/mssql/lib/tedious.js:556:15)
> 			 ....
>        at Parser.readBuffer (/home/myproyect/node_modules/tedious/lib/token/stream-parser.js:430:12)
>      code: 'REQ',
>      number: 156,
>      lineNumber: 1,
>      state: 1,
>      class: 15,
>      serverName: 'SERVERNAME',
>      procName: '',
>      originalError:
>       { Error: Incorrect syntax near the keyword 'NULL'.
>           at handleError (/home/myproyect/node_modules/mssql/lib/tedious.js:554:19)
> 					......
>         info:
>          { number: 156,
>            state: 1,
>            class: 15,
>            message: 'Incorrect syntax near the keyword \'NULL\'.',
>            serverName: 'SERVERNAME',
>            procName: '',
>            lineNumber: 1,
>            name: 'ERROR',
>            event: 'errorMessage' } },
>      name: 'RequestError',
>      precedingErrors: [] },
>   meta: undefined }
>     at Object.connectAndQuery (/home/myproyect/node_modules/sails-mssql/lib/adapter.js:618:69)
>   cause:
>    { Exception: `sendNativeQuery` failed ("queryFailed").  The database returned an error when attempting to execute the native query.
>    Additional data:
>    .......

I did a quick fix changing a line of sql.js file. But I think this file needs a deep review.

**Comment by eckolosst** [comment]
Hello?

**Comment by davepreston** [comment]
_First off, I apologize for my absence. I've been out of commission for a few months because of health issues._

I'm taking a look now, can you give me more info on your environment? what version of sails are you using? how about node?
Any other details you think may be helpful for troubleshooting?

**Comment by eckolosst** [comment]
Hi, it's ok. Sorry about that. Look, this is my package.json:
{
  "name": "nameproject",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "@sailshq/connect-redis": "^3.2.1",
    "@sailshq/lodash": "^3.10.3",
    "@sailshq/socket.io-redis": "^5.2.0",
    "grunt": "1.0.4",
    "machinepack-mssql": "^1.0.0-rc.1.1",
    "request": "^2.88.0",
    "sails": "^1.2.3",
    "sails-hook-cron": "^3.0.0",
    "sails-hook-grunt": "^4.0.0",
    "sails-hook-orm": "^2.1.1",
    "sails-hook-sockets": "^2.0.0",
    "sails-mssql": "^2.0.0"
  },
  "devDependencies": {
    "eslint": "5.16.0"
  },
  "scripts": {
    "start": "NODE_ENV=production node app.js",
    "test": "npm run lint && npm run custom-tests && echo 'Done.'",
    "lint": "./node_modules/eslint/bin/eslint.js . --max-warnings=0 --report-unused-disable-directives && echo '✔  Your .js files look good.'",
    "custom-tests": "echo \"(No other custom tests yet.)\" && echo"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "urlproject"
  },
  "author": "ecko",
  "license": "",
  "engines": {
    "node": "^10.15"
  }
}

The file I changed was sql.js on line 420. There is a kind of mapping of waterline types to mssql data types. mssql do not support double, so i changed this to float.

**Comment by davepreston** [comment]
@eckolosst Thanks for the help identifying this issue (and how you resolved it). I implemented the same solution you did (and will push to NPM momentarily).
